default_context:
  project_name: 'clearn'
  project_slug: 'clearn'
  domain_main: 'clearn.com'
  domain_staging: 'stag.clearn.com'
  docker_swarm_stack_name_main: 'clearn-com'
  docker_swarm_stack_name_staging: 'stag-clearn-com'
  secret_key: 'a7399f376e7fc6d6c4d947da4affa8f42ab87275a581571e96a5469604a8647f'
  first_superuser: 'admin@clearn.com'
  first_superuser_password: 'clearn@123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.clearn.com", "https://stag.clearn.com", "https://clearn.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smpt.gmail.com'
  smtp_user: 'conceptlearning@gmail.com'
  smtp_password: 'clearn@123'
  smtp_emails_from_email: 'info@clearn.com'
  postgres_password: 'clearn@123'
  pgadmin_default_user: 'admin@clearn.com'
  pgadmin_default_user_password: 'clearn@123'
  traefik_constraint_tag: 'clearn.com'
  traefik_constraint_tag_staging: 'stag.clearn.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:clearn@123'
  sentry_dsn: ''
  docker_image_prefix: 'clearn-'
  docker_image_backend: 'clearn-backend'
  docker_image_celeryworker: 'clearn-celeryworker'
  docker_image_frontend: 'clearn-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
